name: marvel_heroes_core
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  
  get:
  dio:
  flutter_svg:
  shared_preferences:
  logger:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
