name: marvel_heroes_core
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  marvel_heroes_commons:
  
  get:
  dio:
  flutter_svg:
  shared_preferences:
  logger:
  shimmer:
  firebase_core:
  firebase_crashlytics:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  marvel_heroes_commons:
    path: ../marvel_heroes_commons