name: marvel_heroes_home
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

dependency_overrides:
  marvel_heroes_commons:
    path: ../marvel_heroes_commons
  marvel_heroes_core:
    path: ../marvel_heroes_core
